#!/bin/sh

for f in *.md; do
    printf "%s\t" "$f"
    res="$(awk -f ../commonmark.awk $f)"
    y="$(cat ${f%.md}.html)"
    if [ "$res" != "$y" ]; then
        echo FAILED!
    else
        echo pass
    fi
done
